/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-03-16 14:21:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.Map;

public final class operations_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


  private String escapeHtml(String value) {
    if (value == null) {
      return "";
    }
    return value
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;");
  }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\r\n");
      out.write("  <title>Patient Analytics</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("  <h2>Analytics</h2>\r\n");
      out.write("\r\n");
      out.write("  ");

    String message = (String) request.getAttribute("message");
    String errorMessage = (String) request.getAttribute("errorMessage");
    Integer totalPatients = (Integer) request.getAttribute("totalPatients");
    String oldestName = (String) request.getAttribute("oldestName");
    String oldestBirthdate = (String) request.getAttribute("oldestBirthdate");
    String oldestCity = (String) request.getAttribute("oldestCity");
    Integer sameCityCount = (Integer) request.getAttribute("sameCityCount");
    String youngestName = (String) request.getAttribute("youngestName");
    String youngestBirthdate = (String) request.getAttribute("youngestBirthdate");
    String youngestCity = (String) request.getAttribute("youngestCity");
    String lookupField = (String) request.getAttribute("lookupField");
    String lookupValue = (String) request.getAttribute("lookupValue");
    Integer lookupCount = (Integer) request.getAttribute("lookupCount");
    Map<String, Integer> raceCounts = (Map<String, Integer>) request.getAttribute("raceCounts");
    Map<String, Integer> topStates = (Map<String, Integer>) request.getAttribute("topStates");
    Map<String, Integer> genderDistribution = (Map<String, Integer>) request.getAttribute("genderDistribution");
    Map<String, Integer> ageBandDistribution = (Map<String, Integer>) request.getAttribute("ageBandDistribution");
    Integer maxAgeBandCount = (Integer) request.getAttribute("maxAgeBandCount");

    if (message != null) {
  
      out.write("\r\n");
      out.write("      <p class=\"message message-success\">");
      out.print( escapeHtml(message) );
      out.write("</p>\r\n");
      out.write("  ");

    }

    if (errorMessage != null) {
  
      out.write("\r\n");
      out.write("      <p class=\"message message-error\">");
      out.print( escapeHtml(errorMessage) );
      out.write("</p>\r\n");
      out.write("  ");

    } else {
  
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <h3>Export Data</h3>\r\n");
      out.write("  <p>Save the current patient data to a JSON file generated from the DataFrame.</p>\r\n");
      out.write("  <form method=\"post\" action=\"saveJson\" class=\"inline-form\">\r\n");
      out.write("    <button type=\"submit\">Save to JSON</button>\r\n");
      out.write("  </form>\r\n");
      out.write("\r\n");
      out.write("  <h3>Summary Statistics</h3>\r\n");
      out.write("  <table class=\"data-table\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th>Statistic</th>\r\n");
      out.write("      <th>Value</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>Total patients</td>\r\n");
      out.write("      <td>");
      out.print( totalPatients );
      out.write("</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>Oldest patient</td>\r\n");
      out.write("      <td>");
      out.print( oldestName );
      out.write(" &mdash; born: ");
      out.print( oldestBirthdate );
      out.write("</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>Oldest patient's city</td>\r\n");
      out.write("      <td>");
      out.print( oldestCity );
      out.write(' ');
      out.write('(');
      out.print( sameCityCount );
      out.write(" patients in this city)</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>Youngest patient</td>\r\n");
      out.write("      <td>");
      out.print( youngestName );
      out.write(" &mdash; born: ");
      out.print( youngestBirthdate );
      out.write("</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>Youngest patient's city</td>\r\n");
      out.write("      <td>");
      out.print( youngestCity );
      out.write("</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("\r\n");
      out.write("  <h3>Field Count Lookup</h3>\r\n");
      out.write("  <p>Select a field and enter a value to count how many patients match.</p>\r\n");
      out.write("  <form method=\"post\" action=\"analytics\" class=\"ops-lookup-form\">\r\n");
      out.write("    <label>Field:\r\n");
      out.write("      <select name=\"lookupField\">\r\n");
      out.write("        <option value=\"CITY\"");
      out.print( "CITY".equals(lookupField) ? " selected" : "" );
      out.write(">City</option>\r\n");
      out.write("        <option value=\"STATE\"");
      out.print( "STATE".equals(lookupField) ? " selected" : "" );
      out.write(">State</option>\r\n");
      out.write("        <option value=\"RACE\"");
      out.print( "RACE".equals(lookupField) ? " selected" : "" );
      out.write(">Race</option>\r\n");
      out.write("        <option value=\"ETHNICITY\"");
      out.print( "ETHNICITY".equals(lookupField) ? " selected" : "" );
      out.write(">Ethnicity</option>\r\n");
      out.write("        <option value=\"GENDER\"");
      out.print( "GENDER".equals(lookupField) ? " selected" : "" );
      out.write(">Gender</option>\r\n");
      out.write("        <option value=\"ZIP\"");
      out.print( "ZIP".equals(lookupField) ? " selected" : "" );
      out.write(">ZIP Code</option>\r\n");
      out.write("        <option value=\"MARITAL\"");
      out.print( "MARITAL".equals(lookupField) ? " selected" : "" );
      out.write(">Marital Status</option>\r\n");
      out.write("      </select>\r\n");
      out.write("    </label>\r\n");
      out.write("    <label>Value:\r\n");
      out.write("      <input type=\"text\" name=\"lookupValue\" value=\"");
      out.print( escapeHtml(lookupValue) );
      out.write("\" />\r\n");
      out.write("    </label>\r\n");
      out.write("    <button type=\"submit\">Count</button>\r\n");
      out.write("  </form>\r\n");
      out.write("  ");

    if (lookupCount != null) {
  
      out.write("\r\n");
      out.write("    <p class=\"message\">Patients where <strong>");
      out.print( escapeHtml(lookupField) );
      out.write("</strong> =\r\n");
      out.write("      &ldquo;<strong>");
      out.print( escapeHtml(lookupValue) );
      out.write("</strong>&rdquo;: <strong>");
      out.print( lookupCount );
      out.write("</strong></p>\r\n");
      out.write("  ");

    }
  
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <h3>Race / Ethnicity Distribution</h3>\r\n");
      out.write("  <table class=\"data-table\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th>Race</th>\r\n");
      out.write("      <th>Count</th>\r\n");
      out.write("      <th>Percentage</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

      if (raceCounts != null && totalPatients != null && totalPatients > 0) {
        for (Map.Entry<String, Integer> entry : raceCounts.entrySet()) {
          double pct = Math.round(entry.getValue() * 1000.0 / totalPatients) / 10.0;
    
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>");
      out.print( escapeHtml(entry.getKey()) );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print( entry.getValue() );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print( pct );
      out.write("%</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

        }
      }
    
      out.write("\r\n");
      out.write("  </table>\r\n");
      out.write("\r\n");
      out.write("  <h3>Age Distribution Chart</h3>\r\n");
      out.write("  <div class=\"simple-chart\">\r\n");
      out.write("    ");

      if (ageBandDistribution != null && !ageBandDistribution.isEmpty()) {
        int maxBarValue = (maxAgeBandCount == null || maxAgeBandCount <= 0) ? 1 : maxAgeBandCount;
        for (Map.Entry<String, Integer> entry : ageBandDistribution.entrySet()) {
          int count = entry.getValue() == null ? 0 : entry.getValue();
          int percentage = (int) Math.round((count * 100.0) / maxBarValue);
    
      out.write("\r\n");
      out.write("      <div class=\"simple-chart-row\">\r\n");
      out.write("        <span class=\"simple-chart-label\">");
      out.print( escapeHtml(entry.getKey()) );
      out.write("</span>\r\n");
      out.write("        <div class=\"simple-chart-track\">\r\n");
      out.write("          <div class=\"simple-chart-bar\" style=\"width: ");
      out.print( percentage );
      out.write("%;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <span class=\"simple-chart-value\">");
      out.print( count );
      out.write("</span>\r\n");
      out.write("      </div>\r\n");
      out.write("    ");

        }
      }
    
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <h3>Top 5 States by Patient Count</h3>\r\n");
      out.write("  <table class=\"data-table\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th>State</th>\r\n");
      out.write("      <th>Count</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

      if (topStates != null) {
        for (Map.Entry<String, Integer> entry : topStates.entrySet()) {
    
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>");
      out.print( escapeHtml(entry.getKey()) );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print( entry.getValue() );
      out.write("</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

        }
      }
    
      out.write("\r\n");
      out.write("  </table>\r\n");
      out.write("\r\n");
      out.write("  <h3>Gender Distribution</h3>\r\n");
      out.write("  <table class=\"data-table\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th>Gender</th>\r\n");
      out.write("      <th>Count</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

      if (genderDistribution != null) {
        for (Map.Entry<String, Integer> entry : genderDistribution.entrySet()) {
    
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td>");
      out.print( escapeHtml(entry.getKey()) );
      out.write("</td>\r\n");
      out.write("      <td>");
      out.print( entry.getValue() );
      out.write("</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");

        }
      }
    
      out.write("\r\n");
      out.write("  </table>\r\n");
      out.write("\r\n");
      out.write("  ");

    }
  
      out.write("\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
