/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-03-18 12:31:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;

public final class patientList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {


  private String escapeHtml(String value) {
    if (value == null) {
      return "";
    }
    return value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;");
  }

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\r\n");
      out.write("  <title>Patient Data App</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("  <h2>Patients:</h2>\r\n");
      out.write("\r\n");
      out.write("  ");

    String errorMessage = (String) request.getAttribute("errorMessage");
    String message = (String) request.getAttribute("message");
    String searchQueryString = (String) request.getAttribute("searchQueryString");
    Integer selectedRow = (Integer) request.getAttribute("selectedRow");
    List<Integer> matchingRows = (List<Integer>) request.getAttribute("matchingRows");
    List<String> summaryColumns = (List<String>) request.getAttribute("summaryColumns");
    List<Map<String, String>> patientRows = (List<Map<String, String>>) request.getAttribute("patientRows");
    Map<String, String> selectedPatient = (Map<String, String>) request.getAttribute("selectedPatient");
    Map<String, String> searchCriteria = (Map<String, String>) request.getAttribute("searchCriteria");
    Integer currentPage = (Integer) request.getAttribute("currentPage");
    Integer totalPages = (Integer) request.getAttribute("totalPages");

    if (searchQueryString == null) searchQueryString = "";
    if (matchingRows == null) matchingRows = java.util.Collections.emptyList();
    if (summaryColumns == null) summaryColumns = java.util.Collections.emptyList();
    if (patientRows == null) patientRows = java.util.Collections.emptyList();
    if (searchCriteria == null) searchCriteria = java.util.Collections.emptyMap();
    if (currentPage == null) currentPage = 1;
    if (totalPages == null) totalPages = 1;

    if (message != null) {
  
      out.write("\r\n");
      out.write("      <p class=\"message message-success\">");
      out.print( escapeHtml(message) );
      out.write("</p>\r\n");
      out.write("  ");

    }

    if (errorMessage != null) {
  
      out.write("\r\n");
      out.write("      <p class=\"message message-error\">");
      out.print( escapeHtml(errorMessage) );
      out.write("</p>\r\n");
      out.write("  ");

    }

    String preservedSearchParameters = searchQueryString.isEmpty() ? "" : "&" + searchQueryString;
  
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <form method=\"get\" action=\"patientList\" class=\"search-form\">\r\n");
      out.write("    <table class=\"data-table search-table\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        ");
 for (String col : summaryColumns) { 
      out.write("\r\n");
      out.write("          <th>");
      out.print( col );
      out.write("</th>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("        ");
 for (String col : summaryColumns) {
             String value = searchCriteria.get(col);
             if (value == null) value = "";
             String valueEscaped = escapeHtml(value);
        
      out.write("\r\n");
      out.write("          <td>\r\n");
      out.write("            <input type=\"text\" name=\"");
      out.print( col );
      out.write("\" value=\"");
      out.print( valueEscaped );
      out.write("\" placeholder=\"");
      out.print( col );
      out.write("\" />\r\n");
      out.write("          </td>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("    <div class=\"search-actions\">\r\n");
      out.write("      <input type=\"submit\" value=\"Search\" />\r\n");
      out.write("      <a href=\"patientList\">Clear</a>\r\n");
      out.write("    </div>\r\n");
      out.write("  </form>\r\n");
      out.write("\r\n");
      out.write("  ");

    if (!matchingRows.isEmpty()) {
  
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <table class=\"data-table\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      ");
 for (String col : summaryColumns) { 
      out.write("\r\n");
      out.write("        <th>");
      out.print( col );
      out.write("</th>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("    </tr>\r\n");
      out.write("\r\n");
      out.write("    ");
 for (Map<String, String> row : patientRows) { 
      out.write("\r\n");
      out.write("      ");
 String rowIndex = row.get("__rowIndex"); 
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("        ");
 for (String col : summaryColumns) { 
      out.write("\r\n");
      out.write("          <td>\r\n");
      out.write("            <a href=\"patientList?page=");
      out.print( currentPage );
      out.print( preservedSearchParameters );
      out.write("&selectedRow=");
      out.print( rowIndex );
      out.write("#details\">");
      out.print( escapeHtml(row.get(col)) );
      out.write("</a>\r\n");
      out.write("          </td>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("      </tr>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("  </table>\r\n");
      out.write("\r\n");
      out.write("  <p>Showing ");
      out.print( matchingRows.size() );
      out.write(" matching records.</p>\r\n");
      out.write("  <p>Page ");
      out.print( currentPage );
      out.write(" of ");
      out.print( totalPages );
      out.write("</p>\r\n");
      out.write("  <div class=\"pagination-links\">\r\n");
      out.write("    ");
 if (currentPage > 1) { 
      out.write("\r\n");
      out.write("      <a href=\"patientList?page=");
      out.print( currentPage - 1 );
      out.print( preservedSearchParameters );
      out.write("\">Previous</a>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    ");
 if (currentPage < totalPages) { 
      out.write("\r\n");
      out.write("      ");
 if (currentPage > 1) { 
      out.write(' ');
      out.write('|');
      out.write(' ');
 } 
      out.write("\r\n");
      out.write("      <a href=\"patientList?page=");
      out.print( currentPage + 1 );
      out.print( preservedSearchParameters );
      out.write("\">Next</a>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <form method=\"get\" action=\"patientList\" class=\"page-form\">\r\n");
      out.write("    ");
 for (String col : summaryColumns) {
         String value = searchCriteria.get(col);
         if (value == null) {
           value = "";
         }
         String valueEscaped = escapeHtml(value);
    
      out.write("\r\n");
      out.write("      <input type=\"hidden\" name=\"");
      out.print( col );
      out.write("\" value=\"");
      out.print( valueEscaped );
      out.write("\" />\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    <label for=\"pageInput\">Go to page:</label>\r\n");
      out.write("    <input id=\"pageInput\" type=\"number\" name=\"page\" min=\"1\" max=\"");
      out.print( totalPages );
      out.write("\" value=\"");
      out.print( currentPage );
      out.write("\" required />\r\n");
      out.write("    <input type=\"submit\" value=\"Go\" />\r\n");
      out.write("  </form>\r\n");
      out.write("\r\n");
      out.write("  ");

    if (selectedRow != null) {
  
      out.write("\r\n");
      out.write("  <h3 id=\"details\">Patient Details</h3>\r\n");
      out.write("  <table class=\"data-table\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <th>Field</th>\r\n");
      out.write("      <th>Value</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    ");
 for (Map.Entry<String, String> entry : selectedPatient.entrySet()) { 
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>");
      out.print( escapeHtml(entry.getKey()) );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( escapeHtml(entry.getValue()) );
      out.write("</td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("  </table>\r\n");
      out.write("\r\n");
      out.write("  <h3>Edit Patient</h3>\r\n");
      out.write("  <form method=\"post\" action=\"updatePatient\" class=\"patient-edit-form\">\r\n");
      out.write("    <input type=\"hidden\" name=\"rowIndex\" value=\"");
      out.print( selectedRow );
      out.write("\" />\r\n");
      out.write("    <input type=\"hidden\" name=\"page\" value=\"");
      out.print( currentPage );
      out.write("\" />\r\n");
      out.write("    <input type=\"hidden\" name=\"returnQuery\" value=\"");
      out.print( escapeHtml(searchQueryString) );
      out.write("\" />\r\n");
      out.write("    <table class=\"data-table\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th>Field</th>\r\n");
      out.write("        <th>Value</th>\r\n");
      out.write("      </tr>\r\n");
      out.write("      ");
 for (Map.Entry<String, String> entry : selectedPatient.entrySet()) { 
      out.write("\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>");
      out.print( escapeHtml(entry.getKey()) );
      out.write("</td>\r\n");
      out.write("        <td>\r\n");
      out.write("          <input class=\"patient-edit-input\" type=\"text\" name=\"");
      out.print( escapeHtml(entry.getKey()) );
      out.write("\" value=\"");
      out.print( escapeHtml(entry.getValue()) );
      out.write("\" />\r\n");
      out.write("        </td>\r\n");
      out.write("      </tr>\r\n");
      out.write("      ");
 } 
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("    <div class=\"search-actions\">\r\n");
      out.write("      <input type=\"submit\" value=\"Save Changes\" />\r\n");
      out.write("    </div>\r\n");
      out.write("  </form>\r\n");
      out.write("\r\n");
      out.write("  <form method=\"post\" action=\"deletePatient\" class=\"delete-form\">\r\n");
      out.write("    <input type=\"hidden\" name=\"rowIndex\" value=\"");
      out.print( selectedRow );
      out.write("\" />\r\n");
      out.write("    <input type=\"hidden\" name=\"page\" value=\"");
      out.print( currentPage );
      out.write("\" />\r\n");
      out.write("    <input type=\"hidden\" name=\"returnQuery\" value=\"");
      out.print( escapeHtml(searchQueryString) );
      out.write("\" />\r\n");
      out.write("    <input type=\"submit\" value=\"Delete Patient\" onclick=\"return confirm('Delete this patient?');\" />\r\n");
      out.write("  </form>\r\n");
      out.write("  ");

    }
  
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");

    } else {
  
      out.write("\r\n");
      out.write("      <p>No patient records match your search.</p>\r\n");
      out.write("  ");

    }
  
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
